In [9]:
import numpy as np
import sys 

In [12]:
a = np.array([1, 2, 3, 4, 5])
a[1:3] =10
a

array([ 1, 10, 10,  4,  5])

In [14]:
a [[1,3]]

array([10,  4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([ 1, 1.0, 0.25])
b.dtype

dtype('float64')

In [17]:
np.array([1,2,3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.shape
A[1][2]
A[0:2]
A.sum(axis=1)

array([ 6, 15, 24])

In [2]:
import numpy as np

In [ ]:
c = np.arange(10)
c
c+10
c+=10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
l=[0,1,2,3]
[i*10 for i in l]

[0, 10, 20, 30]

In [12]:
x = np.arange(4)
y = np.array([10, 10, 10, 10])
x + y
x * y

array([ 0, 10, 20, 30])

In [13]:
a = np.arange(4)
a <=2

array([ True,  True,  True, False])

In [14]:
a.mean()

np.float64(1.5)

In [15]:
a[ (a<=2) & (a>=1) ]

array([1, 2])

In [16]:
z = np.random.randint(100, size=(3,3))
z

array([[32, 35, 51],
       [57, 30, 45],
       [73, 42, 13]], dtype=int32)

In [ ]:
#Linear algebra

